// <auto-generated />
namespace EdgeRealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class afterLocal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(afterLocal));
        
        string IMigrationMetadata.Id
        {
            get { return "202001251147108_afterLocal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
