// <auto-generated />
namespace EdgeRealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class _123_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001250952020_123_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
